<a href="https://colab.research.google.com/github/navaneecivil984-ai/AIML-PREREQ-LEARNER/blob/main/python_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=1
b=2
c=3
print(a+b+c)
print("a+b+c")

6
a+b+c


In [ ]:
# Define variables of different types
int_variable = 10
float_variable = 20.5
string_variable = "Hello, Colab!"
bool_variable = True

# Perform a simple operation with numeric variables
sum_of_numbers = int_variable + float_variable

# Print the variables and their types
print(f"Integer variable: {int_variable} (type: {type(int_variable)})")
print(f"Float variable: {float_variable} (type: {type(float_variable)})")
print(f"String variable: {string_variable} (type: {type(string_variable)})")
print(f"Boolean variable: {bool_variable} (type: {type(bool_variable)})")
print(f"Sum of int and float: {sum_of_numbers} (type: {type(sum_of_numbers)})")

Integer variable: 10 (type: <class 'int'>)
Float variable: 20.5 (type: <class 'float'>)
String variable: Hello, Colab! (type: <class 'str'>)
Boolean variable: True (type: <class 'bool'>)
Sum of int and float: 30.5 (type: <class 'float'>)


In [ ]:
import gradio as gr

class Room:
    def __init__(self, room_number, room_type, price):
        self.room_number = room_number
        self.room_type = room_type # e.g., 'single', 'double', 'suite'
        self.price = price
        self.is_available = True

    def __str__(self):
        status = "Available" if self.is_available else "Booked"
        return f"Room {self.room_number} ({self.room_type}) - ${self.price:.2f} per night [{status}]"

class Hotel:
    def __init__(self, name):
        self.name = name
        self.rooms = {}
        self.bookings = {}
        self.next_booking_id = 1

    def add_room(self, room_number, room_type, price):
        if room_number not in self.rooms:
            new_room = Room(room_number, room_type, price)
            self.rooms[room_number] = new_room
            return f"Room {room_number} ({room_type}) added to {self.name}."
        else:
            return f"Room {room_number} already exists."

    def get_available_rooms_str(self):
        available_rooms = [room for room in self.rooms.values() if room.is_available]
        if not available_rooms:
            return "No rooms currently available."
        else:
            return "\n".join([str(room) for room in available_rooms])

    def book_room(self, room_number, guest_name):
        if room_number in self.rooms and self.rooms[room_number].is_available:
            room = self.rooms[room_number]
            room.is_available = False
            booking_id = self.next_booking_id
            self.bookings[booking_id] = {'room': room, 'guest': guest_name}
            self.next_booking_id += 1
            return f"Booking {booking_id}: Room {room_number} booked for {guest_name}."
        else:
            return f"Room {room_number} is not available or does not exist."

    def check_out_room(self, booking_id):
        if booking_id in self.bookings:
            booking_info = self.bookings[booking_id]
            room = booking_info['room']
            guest = booking_info['guest']
            room.is_available = True
            del self.bookings[booking_id]
            return f"Guest {guest} checked out from Room {room.room_number}. Booking {booking_id} cancelled."
        else:
            return f"Booking {booking_id} not found."

    def get_hotel_status_str(self):
        status_output = f"--- {self.name} Status ---\n"
        status_output += "Rooms:\n"
        if not self.rooms:
            status_output += "  No rooms defined.\n"
        else:
            for room in self.rooms.values():
                status_output += f"  {room}\n"
        status_output += "Bookings:\n"
        if not self.bookings:
            status_output += "  No active bookings.\n"
        else:
            for booking_id, info in self.bookings.items():
                status_output += f"  Booking {booking_id}: Room {info['room'].room_number} for {info['guest']}\n"
        status_output += "----------------------"
        return status_output

# Instantiate the Hotel
my_hotel = Hotel("Grand Python Hotel")

# Gradio Interface
with gr.Blocks(title="Hotel Management App") as demo:
    gr.Markdown("# Grand Python Hotel Management")

    with gr.Tab("Add Room"):
        gr.Markdown("## Add a New Room")
        room_num_input = gr.Number(label="Room Number (e.g., 101)", interactive=True)
        room_type_input = gr.Dropdown(["single", "double", "suite"], label="Room Type", interactive=True)
        room_price_input = gr.Number(label="Price per Night", interactive=True)
        add_room_btn = gr.Button("Add Room")
        add_room_output = gr.Textbox(label="Result")
        add_room_btn.click(my_hotel.add_room, inputs=[room_num_input, room_type_input, room_price_input], outputs=add_room_output)

    with gr.Tab("Book Room"):
        gr.Markdown("## Book a Room")
        book_room_num_input = gr.Number(label="Room Number to Book", interactive=True)
        guest_name_input = gr.Textbox(label="Guest Name", interactive=True)
        book_room_btn = gr.Button("Book Room")
        book_room_output = gr.Textbox(label="Result")
        book_room_btn.click(my_hotel.book_room, inputs=[book_room_num_input, guest_name_input], outputs=book_room_output)

    with gr.Tab("Check Out"):
        gr.Markdown("## Check Out Guest")
        booking_id_input = gr.Number(label="Booking ID", interactive=True)
        checkout_btn = gr.Button("Check Out")
        checkout_output = gr.Textbox(label="Result")
        checkout_btn.click(my_hotel.check_out_room, inputs=[booking_id_input], outputs=checkout_output)

    with gr.Tab("Hotel Status & Available Rooms"):
        gr.Markdown("## Current Hotel Status")
        status_btn = gr.Button("Refresh Status")
        hotel_status_output = gr.Textbox(label="Hotel Status", lines=10)
        available_rooms_output = gr.Textbox(label="Available Rooms", lines=5)
        status_btn.click(my_hotel.get_hotel_status_str, inputs=[], outputs=hotel_status_output)
        status_btn.click(my_hotel.get_available_rooms_str, inputs=[], outputs=available_rooms_output)

# Launch the Gradio app
demo.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://9f2b369899b46067f3.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


In [ ]:
# Get the first number from the user
num1_str = input("Enter the first number: ")

# Get the second number from the user
num2_str = input("Enter the second number: ")

# Convert the input strings to integers (or floats if decimal numbers are expected)
try:
    num1 = int(num1_str)
    num2 = int(num2_str)

    # Calculate the sum
    total_sum = num1 + num2

    # Print the result
    print(f"The sum of {num1} and {num2} is: {total_sum}")
except ValueError:
    print("Invalid input. Please enter valid numbers.")

Enter the first number: 12
Enter the second number: 200
The sum of 12 and 200 is: 212


In [ ]:
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

sum_of_numbers = num1 + num2

print(f"The sum of {num1} and {num2} is: {sum_of_numbers}")

In [ ]:
import gradio as gr

def add_numbers(num1, num2):
    try:
        # Convert inputs to numbers (float to handle decimals)
        number1 = float(num1)
        number2 = float(num2)
        return number1 + number2
    except ValueError:
        return "Please enter valid numbers"

# Create the Gradio interface
interface = gr.Interface(
    fn=add_numbers,
    inputs=[
        gr.Number(label="First Number"),
        gr.Number(label="Second Number")
    ],
    outputs=gr.Number(label="Sum"),
    title="Simple Addition App",
    description="Enter two numbers and get their sum!"
)

# Launch the interface
interface.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://a0568d6e780de77355.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


In [ ]:
class Room:
    def __init__(self, room_number, room_type, price):
        self.room_number = room_number
        self.room_type = room_type # e.g., 'single', 'double', 'suite'
        self.price = price
        self.is_available = True

    def __str__(self):
        status = "Available" if self.is_available else "Booked"
        return f"Room {self.room_number} ({self.room_type}) - ${self.price:.2f} per night [{status}]"

class Hotel:
    def __init__(self, name):
        self.name = name
        self.rooms = {}
        self.bookings = {}
        self.next_booking_id = 1

    def add_room(self, room_number, room_type, price):
        if room_number not in self.rooms:
            new_room = Room(room_number, room_type, price)
            self.rooms[room_number] = new_room
            print(f"Room {room_number} ({room_type}) added to {self.name}.")
        else:
            print(f"Room {room_number} already exists.")

    def get_available_rooms(self):
        available_rooms = [room for room in self.rooms.values() if room.is_available]
        if not available_rooms:
            print("No rooms currently available.")
        else:
            print("\nAvailable Rooms:")
            for room in available_rooms:
                print(room)
        return available_rooms

    def book_room(self, room_number, guest_name):
        if room_number in self.rooms and self.rooms[room_number].is_available:
            room = self.rooms[room_number]
            room.is_available = False
            booking_id = self.next_booking_id
            self.bookings[booking_id] = {'room': room, 'guest': guest_name}
            self.next_booking_id += 1
            print(f"Booking {booking_id}: Room {room_number} booked for {guest_name}.")
            return booking_id
        else:
            print(f"Room {room_number} is not available or does not exist.")
            return None

    def check_out_room(self, booking_id):
        if booking_id in self.bookings:
            booking_info = self.bookings[booking_id]
            room = booking_info['room']
            guest = booking_info['guest']
            room.is_available = True
            del self.bookings[booking_id]
            print(f"Guest {guest} checked out from Room {room.room_number}. Booking {booking_id} cancelled.")
        else:
            print(f"Booking {booking_id} not found.")

    def display_hotel_status(self):
        print(f"\n--- {self.name} Status ---")
        print("Rooms:")
        if not self.rooms:
            print("  No rooms defined.")
        else:
            for room in self.rooms.values():
                print(f"  {room}")
        print("Bookings:")
        if not self.bookings:
            print("  No active bookings.")
        else:
            for booking_id, info in self.bookings.items():
                print(f"  Booking {booking_id}: Room {info['room'].room_number} for {info['guest']}")
        print("----------------------")

# --- Example Usage --- #
if __name__ == '__main__':
    my_hotel = Hotel("Grand Python Hotel")

    # Add some rooms
    my_hotel.add_room(101, 'single', 100.00)
    my_hotel.add_room(102, 'double', 150.00)
    my_hotel.add_room(201, 'suite', 300.00)
    my_hotel.add_room(202, 'double', 160.00)

    # Display initial status and available rooms
    my_hotel.display_hotel_status()
    my_hotel.get_available_rooms()

    # Book a room
    booking1 = my_hotel.book_room(102, 'Alice Smith')
    booking2 = my_hotel.book_room(201, 'Bob Johnson')

    # Try to book an unavailable room
    my_hotel.book_room(102, 'Charlie Brown')

    # Display status after bookings
    my_hotel.display_hotel_status()
    my_hotel.get_available_rooms()

    # Check out a guest
    if booking1:
        my_hotel.check_out_room(booking1)

    # Display final status
    my_hotel.display_hotel_status()
    my_hotel.get_available_rooms()


Room 101 (single) added to Grand Python Hotel.
Room 102 (double) added to Grand Python Hotel.
Room 201 (suite) added to Grand Python Hotel.
Room 202 (double) added to Grand Python Hotel.

--- Grand Python Hotel Status ---
Rooms:
  Room 101 (single) - $100.00 per night [Available]
  Room 102 (double) - $150.00 per night [Available]
  Room 201 (suite) - $300.00 per night [Available]
  Room 202 (double) - $160.00 per night [Available]
Bookings:
  No active bookings.
----------------------

Available Rooms:
Room 101 (single) - $100.00 per night [Available]
Room 102 (double) - $150.00 per night [Available]
Room 201 (suite) - $300.00 per night [Available]
Room 202 (double) - $160.00 per night [Available]
Booking 1: Room 102 booked for Alice Smith.
Booking 2: Room 201 booked for Bob Johnson.
Room 102 is not available or does not exist.

--- Grand Python Hotel Status ---
Rooms:
  Room 101 (single) - $100.00 per night [Available]
  Room 102 (double) - $150.00 per night [Booked]
  Room 201 (suit

In [ ]:
class Room:
    def __init__(self, room_number, room_type, price):
        self.room_number = room_number
        self.room_type = room_type # e.g., 'single', 'double', 'suite'
        self.price = price
        self.is_available = True

    def __str__(self):
        status = "Available" if self.is_available else "Booked"
        return f"Room {self.room_number} ({self.room_type}) - ${self.price:.2f} per night [{status}]"

class Hotel:
    def __init__(self, name):
        self.name = name
        self.rooms = {}
        self.bookings = {}
        self.next_booking_id = 1

    def add_room(self, room_number, room_type, price):
        if room_number not in self.rooms:
            new_room = Room(room_number, room_type, price)
            self.rooms[room_number] = new_room
            print(f"Room {room_number} ({room_type}) added to {self.name}.")
        else:
            print(f"Room {room_number} already exists.")

    def get_available_rooms(self):
        available_rooms = [room for room in self.rooms.values() if room.is_available]
        if not available_rooms:
            print("No rooms currently available.")
        else:
            print("\nAvailable Rooms:")
            for room in available_rooms:
                print(room)
        return available_rooms

    def book_room(self, room_number, guest_name):
        if room_number in self.rooms and self.rooms[room_number].is_available:
            room = self.rooms[room_number]
            room.is_available = False
            booking_id = self.next_booking_id
            self.bookings[booking_id] = {'room': room, 'guest': guest_name}
            self.next_booking_id += 1
            print(f"Booking {booking_id}: Room {room_number} booked for {guest_name}.")
            return booking_id
        else:
            print(f"Room {room_number} is not available or does not exist.")
            return None

    def check_out_room(self, booking_id):
        if booking_id in self.bookings:
            booking_info = self.bookings[booking_id]
            room = booking_info['room']
            guest = booking_info['guest']
            room.is_available = True
            del self.bookings[booking_id]
            print(f"Guest {guest} checked out from Room {room.room_number}. Booking {booking_id} cancelled.")
        else:
            print(f"Booking {booking_id} not found.")

    def display_hotel_status(self):
        print(f"\n--- {self.name} Status ---")
        print("Rooms:")
        if not self.rooms:
            print("  No rooms defined.")
        else:
            for room in self.rooms.values():
                print(f"  {room}")
        print("Bookings:")
        if not self.bookings:
            print("  No active bookings.")
        else:
            for booking_id, info in self.bookings.items():
                print(f"  Booking {booking_id}: Room {info['room'].room_number} for {info['guest']}")
        print("----------------------")

# --- Example Usage --- #
if __name__ == '__main__':
    my_hotel = Hotel("Grand Python Hotel")

    # Add some rooms
    my_hotel.add_room(101, 'single', 100.00)
    my_hotel.add_room(102, 'double', 150.00)
    my_hotel.add_room(201, 'suite', 300.00)
    my_hotel.add_room(202, 'double', 160.00)

    # Display initial status and available rooms
    my_hotel.display_hotel_status()
    my_hotel.get_available_rooms()

    # Book a room
    booking1 = my_hotel.book_room(102, 'Alice Smith')
    booking2 = my_hotel.book_room(201, 'Bob Johnson')

    # Try to book an unavailable room
    my_hotel.book_room(102, 'Charlie Brown')

    # Display status after bookings
    my_hotel.display_hotel_status()
    my_hotel.get_available_rooms()

    # Check out a guest
    if booking1:
        my_hotel.check_out_room(booking1)

    # Display final status
    my_hotel.display_hotel_status()
    my_hotel.get_available_rooms()

Room 101 (single) added to Grand Python Hotel.
Room 102 (double) added to Grand Python Hotel.
Room 201 (suite) added to Grand Python Hotel.
Room 202 (double) added to Grand Python Hotel.

--- Grand Python Hotel Status ---
Rooms:
  Room 101 (single) - $100.00 per night [Available]
  Room 102 (double) - $150.00 per night [Available]
  Room 201 (suite) - $300.00 per night [Available]
  Room 202 (double) - $160.00 per night [Available]
Bookings:
  No active bookings.
----------------------

Available Rooms:
Room 101 (single) - $100.00 per night [Available]
Room 102 (double) - $150.00 per night [Available]
Room 201 (suite) - $300.00 per night [Available]
Room 202 (double) - $160.00 per night [Available]
Booking 1: Room 102 booked for Alice Smith.
Booking 2: Room 201 booked for Bob Johnson.
Room 102 is not available or does not exist.

--- Grand Python Hotel Status ---
Rooms:
  Room 101 (single) - $100.00 per night [Available]
  Room 102 (double) - $150.00 per night [Booked]
  Room 201 (suit

matrix

In [ ]:
import numpy as np

# Create two matrices
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("Matrix A:\n", matrix_a)
print("\nMatrix B:\n", matrix_b)



Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
# Perform mathematical operations

# Addition
matrix_sum = matrix_a + matrix_b
print("\nMatrix A + Matrix B:\n", matrix_sum)

# Subtraction
matrix_diff = matrix_a - matrix_b
print("\nMatrix A - Matrix B:\n", matrix_diff)

# Element-wise Multiplication (Hadamard product)
matrix_elem_wise_prod = matrix_a * matrix_b
print("\nElement-wise product (A * B):\n", matrix_elem_wise_prod)

# Matrix Multiplication (Dot product)
# For dot product, the number of columns in the first matrix must be equal to the number of rows in the second matrix.
# In this case, both are 3x3, so it's compatible.
matrix_dot_prod = np.dot(matrix_a, matrix_b)
print("\nMatrix multiplication (A @ B):\n", matrix_dot_prod)

# Scalar Multiplication
scalar_multiplier = 2
matrix_scalar_prod = matrix_a * scalar_multiplier
print(f"\nMatrix A * {scalar_multiplier}:\n", matrix_scalar_prod)


Matrix A + Matrix B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix A - Matrix B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise product (A * B):
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix multiplication (A @ B):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Matrix A * 2:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
import numpy as np

# Scalar Matrix: A diagonal matrix where all diagonal elements are equal
scalar_value = 5
scalar_matrix = scalar_value * np.eye(3) # Creates a 3x3 identity matrix and scales it
print("\nScalar Matrix (5 * I):\n", scalar_matrix)

# Vector Matrix: Representing vectors as matrices (row and column vectors)
vector_row = np.array([10, 11, 12])
vector_column = np.array([[10], [11], [12]])

print("\nRow Vector (1D array):\n", vector_row)
print("Shape of Row Vector:", vector_row.shape)

print("\nColumn Vector (2D array):\n", vector_column)
print("Shape of Column Vector:", vector_column.shape)

# Transpose Matrix: Swapping rows and columns of an existing matrix
matrix_c = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal Matrix C:\n", matrix_c)

matrix_c_transpose = matrix_c.T # Using the .T attribute for transpose
print("\nTranspose of Matrix C:\n", matrix_c_transpose)

# Example with matrix_a (assuming matrix_a is defined in a previous cell)
try:
    print("\nOriginal matrix_a:\n", matrix_a)
    print("\nTranspose of matrix_a:\n", matrix_a.T)
except NameError:
    print("\nmatrix_a is not defined. Please run the cell where matrix_a is created first.")


Scalar Matrix (5 * I):
 [[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]

Row Vector (1D array):
 [10 11 12]
Shape of Row Vector: (3,)

Column Vector (2D array):
 [[10]
 [11]
 [12]]
Shape of Column Vector: (3, 1)

Original Matrix C:
 [[1 2 3]
 [4 5 6]]

Transpose of Matrix C:
 [[1 4]
 [2 5]
 [3 6]]

Original matrix_a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of matrix_a:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
